default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: week_3_code_review_development

test:
  <<: *default
  database: week_3_code_review_test

production:
  <<: *default
  database: week_3_code_review_production
  username: week_3_code_review
  password: <%= ENV['WEEK_3_CODE_REVIEW_DATABASE_PASSWORD'] %>
